doc:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**'
      - 'LICENSE*'

code:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.mjs'
      - '**/*.cjs'
      - '**/*.rs'
      - 'src/**'

dep:
  - changed-files:
    - any-glob-to-any-file:
      - 'package.json'
      - 'package-lock.json'
      - 'bun.lock'
      - 'deno.lock'
      - 'deno.json'
      - 'Cargo.toml'
      - 'Cargo.lock'

config:
  - changed-files:
    - any-glob-to-any-file:
      - 'tsconfig*.json'
      - '*.config.*'
      - '.*rc'
      - '.*rc.*'
      - '.github/**'
      - '.husky/**'
